-- ==========================================
-- SCRIPT DE INICIALIZAÇÃO DE SCHEMAS - SUPABASE
-- Execute este script no SQL Editor do seu Supabase
-- ==========================================

-- ------------------------------------------
-- 1. CAMADA BRONZE (PAYLOADS BRUTOS JSONB)
-- ------------------------------------------

CREATE TABLE IF NOT EXISTS public.bronze_squad (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    extracted_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    data JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS public.bronze_fixtures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    extracted_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    data JSONB NOT NULL
);

-- ------------------------------------------
-- 2. CAMADA SILVER (DADOS RELACIONAIS E TIPADOS)
-- ------------------------------------------

CREATE TABLE IF NOT EXISTS public.silver_squad (
    player_id BIGINT PRIMARY KEY,
    name TEXT NOT NULL,
    position TEXT,
    nationality TEXT,
    jersey_number INTEGER,
    birth_date DATE,
    height TEXT,
    weight TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.silver_fixtures (
    fixture_id BIGINT PRIMARY KEY,
    date TIMESTAMP WITH TIME ZONE,
    status TEXT,
    home_team TEXT,
    away_team TEXT,
    home_score INTEGER,
    away_score INTEGER,
    venue TEXT,
    winner_id BIGINT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ------------------------------------------
-- 3. CAMADA GOLD (VISÕES E INDICADORES ANALÍTICOS)
-- ------------------------------------------

CREATE TABLE IF NOT EXISTS public.gold_squad_summary (
    position TEXT PRIMARY KEY,
    player_count INTEGER NOT NULL,
    average_age NUMERIC(4,2),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.gold_fixtures_summary (
    team_name TEXT PRIMARY KEY,
    total_games INTEGER NOT NULL,
    wins INTEGER NOT NULL,
    draws INTEGER NOT NULL,
    losses INTEGER NOT NULL,
    goals_scored INTEGER NOT NULL,
    goals_conceded INTEGER NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ------------------------------------------
-- 4. ÍNDICES DE PERFORMANCE (OPCIONAL)
-- ------------------------------------------
CREATE INDEX IF NOT EXISTS idx_silver_fixtures_date ON public.silver_fixtures (date);
CREATE INDEX IF NOT EXISTS idx_silver_squad_position ON public.silver_squad (position);
